#Kotlin
kotlin.code.style=official
# kotlin.daemon.jvmargs=-Xmx3072M
# Increase Kotlin Daemon Heap (used for compilation)
kotlin.daemon.jvmargs=-Xmx6144M

#Gradle
# org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
# Increase Gradle JVM Heap
org.gradle.jvmargs=-Xmx6144M -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

